language: objective-c

before_install:
  - brew install webp icu4c boost proj jpeg libtiff harfbuzz

install:
  - true

before_script:
  - true

script:
 - ./configure CXX="${CXX}" CC="${CC}"
 - make
 - make test
