language: objective-c

before_install:
  - brew update
  - brew rm boost
  - brew install webp icu4c boost boost-python proj jpeg libtiff harfbuzz

install:
  - true

before_script:
  - true

script:
 - ./configure CXX="${CXX}" CC="${CC}"
 - make
 - make test
